.TH CLP 1
.SH NAME
clp \- print files to stdout with syntax highlighting
.SH SYNOPSIS
.B clp
[\fb\-t\fr \fifiletype\fr]
[\fb\-\-override-filetype\fr \fifiletype\fr]
[\fb\-l\fr]
[\fb\-\-list-overrides\fr]
file
.SH DESCRIPTION
.B clp
reads an input file, determines its language from its filetype, and writes it to stdout with syntax highlighting.
.SH OPTIONS
.TP
.BR \-l ", " \-\-list-overrides
See below.
.TP
.BR \-t ", " \-\-override-filetype=\fIFILETYPE\fR
Force a language's syntax for highlighting the file. To see available filetypes, run \fBclp \-\-list\-overrides\fR\
