.TH CLP 1
.SH NAME
clp \- print files to stdout with syntax highlighting
.SH SYNOPSIS
.B clp
[\fboptions\fr]
file
.SH DESCRIPTION
.B clp
Reads an input file, determines its language from its filetype, and writes it to stdout with syntax highlighting.
.SH OPTIONS
.HP
\fB\-l\fR, \fB\-\-list\-overrides\fR
.IP
See below.
.HP
\fB\-t\fR, \fB\-\-override\-filetype\fR {filetype}
.IP
Force a language's syntax for highlighting the file. To see available filetypes, run \fBclp \-\-list\-overrides\fR\

.HP
\fB\-h\fR, \fB\-\-highlight\-line\fR {number}
.IP
Highlight a non-blank line
