.TH CLP 1
.SH NAME
clp \- print files to stdout with syntax highlighting
.SH SYNOPSIS
.B clp
[\fboptions\fr]
file
.SH DESCRIPTION
.B clp
Reads an input file, determines its language from its filetype, and writes it to stdout with syntax highlighting.
.SH OPTIONS
.HP
\fB\-l\fR, \fB\-\-list\-overrides\fR
.IP
See below.
.HP
\fB\-t\fR, \fB\-\-override\-filetype\fR {filetype}
.IP
Force a language's syntax for highlighting the file. To see available filetypes, run \fBclp \-\-list\-overrides\fR
.HP
\fB\-t\fR, \fB\-\-override\-colortheme\fR {filetype}
.IP
Override the color theme defined in clprc.lua \fR
.HP
\fB\-h\fR, \fB\-\-highlight\-line\fR {number}
.IP
Highlight a non-blank line
.SH FILES
Upon startup
.Nm
will source the first \fBclprc.lua\fR configuration file found from these locations.
.Bl -bullet
.IP \[bu] 2
\fB$CLP_PATH\fR if set or \fB/usr/local/share/clp\fR or if not
.IP \[bu] 2
The source directory where the project was built (when built from source)
.IP \[bu] 2
\fB$XDG_CONFIG_HOME/clp\fR or \fB$HOME/.config\fR if \fBXDG_CONFIG_HOME\fR is not set
.HP
When creating a new \fBclprc.lua\fR be sure to copy the structure from here.
.SH CONFIGURATION
\fBclp\fR is configured by the \fBclprc.lua\fR file described in the \fBFILES\fR section.
.HP
To change your colorscheme, set \fBclprc.theme = "{colorscheme name}"\fR in \fBclprc.lua\fR. A complete list of built-in colorschemes is available at \fBhttps://sr.ht/~eskin/clp/#setting-your-colorscheme\fR
.HP
Additional colorschemes can be installed to a "themes" folder in your clp configuration folder. For more information, see the README at \fBhttps://sr.ht/~eskin/clp/#configuration\fR


